### PR TITLE
chore: Bump deps

### PR DESCRIPTION
**Pull request by JorTurFer**

### CODE REVIEW

**Review by dgrisonnet — COMMENTED** [review]
/ok-to-test

**Comment by JorTurFer** [comment]
> @JorTurFer could you run `update-generated` and push the updated files?

Sure, done!
Sorry because I forgot it at the first time :(

**Comment by dgrisonnet** [comment]
No worries at, all thank you for doing the bump! :)

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
