### PR TITLE
Update kubernetes-incubator references to kubernetes-sigs

### LINKED ISSUE #69: Update references to kubernetes-incubator
The [kubernetes-incubator org](http://github.com/kubernetes-incubator) has been deprecated - https://github.com/kubernetes/community/issues/1922.

This repo still contains `kubernetes-incubator` in it's Makefile and import paths, so these should be updated.

### PR DESCRIPTION
**Pull request by dgrisonnet**
Fixes #69

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]

**Comment by s-urbaniak** [comment]
awesome, thank you!

**Pull request merged**
