### PR TITLE
chore: Bump k8s deps to 0.31.2

### PR DESCRIPTION
**Pull request by JorTurFer**
We are preparing the new KEDA release and we want to bump k8s deps. This PR bumps k8s deps to 0.31. Could you merge this PR and ship a release?

### CODE REVIEW

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Comment by JorTurFer** [comment]
I've fixed the PR issues 😄

**Review by dgrisonnet — APPROVED** [review]
/lgtm

**Comment by RainbowMango** [comment]
@dgrisonnet any plan to tag a new release for this?

**Comment by RainbowMango** [comment]
For guys who are waiting for the new release, you can use the pseudo version(`v1.30.1-0.20241105195130-84dc8cfe2555`) temporarily.

**Pull request merged**
