### PR TITLE
Bump k8s.io/client-go and k8s.io/apiserver to v0.26.0

### PR DESCRIPTION
**Pull request by dttung2905**
Hi team,

Happy New Year! 
This MR is meant to bump  `k8s.io/client-go` and `k8s.io/apiserver` to v0.26.0.

There was a refactoring for method `WriteObjectNegotiated()` that requires a minor change ([source](https://github.com/kubernetes/apiserver/commit/0a2a637e8570e478af5b4e85fdf226e5d8c13e48#diff-274d22eb12a038fe95b5e359c893350c8e57805ae54bd0dbba28d7bae41f5af8R262))

Reason: This MR is a prerequisite for this issue in KEDA kedacore/keda#4013 where we want benefit from some new features in `k8s.io/client-go`  v0.26.0
https://github.com/kedacore/keda/blob/64e734bad185ecc93dee2d2df67ea0a3a65b0845/go.mod#L88

Please let me know your feedback on this. :pray:

### CODE REVIEW

**Review by olivierlemasle — CHANGES_REQUESTED** [review]
Seems good, thanks @dttung2905!

Just one thing: please update the generated OpenAPI definitions by running:

```bash
touch go.mod    # to force the generation if needed
make
```

(it should be detected by CI but it is not verified yet)

/triage accepted

**Comment by dttung2905** [comment]
> Seems good, thanks @\dttung2905!
> 
> Just one thing: please update the generated OpenAPI definitions by running:
> 
> ```shell
> touch go.mod    # to force the generation if needed
> make
> ```
> 
> (it should be detected by CI but it is not verified yet)
> 
> /triage accepted


Thanks alot @olivierlemasle for the super quick review! . I have generated OpenAPI definitions as you suggested. Could you help to review it again :pray: ?

**Review by olivierlemasle — APPROVED** [review]
Thank you @dttung2905 

/lgtm
/assign @dgrisonnet

**Comment by dgrisonnet** [comment]
Awesome, thank you @dttung2905!

/approve
/lgtm

**Pull request merged**
