### PR TITLE
make metrics provider context-aware

### PR DESCRIPTION
**Pull request by answer1991**
make metrics provider context-aware

Signed-off-by: answer1991 <answer1991.chen@gmail.com>

### CODE REVIEW

**Comment by zroubalik** [comment]
This is a breaking change, since you are changing the interface. We should be careful about this.

**Comment by answer1991** [comment]
yes, user update their vendor of this repo should change their implement. However, the change is a reasonable improvement.

**Comment by dgrisonnet** [comment]
I agree that we should be careful not to introduce breaking changes before a real release process is in place. Thus, I'd suggest waiting for #67 before moving forward with this.
That being said, I think making providers context aware would be a great addition.

**Comment by dgrisonnet** [comment]
/lgtm
/approve

Holding until #89 is done since this is a breaking change for the consumers of the library.

/hold

**Pull request merged**
