### PR TITLE
[BUG] fix kube-openapi's changes

### PR DESCRIPTION
**Pull request by dashanji**
The PR is to fix a bug related to [kube-openapi's changes](https://github.com/kubernetes/kube-openapi/pull/234).

**How to reproduce the bug?**

My go version is `go version go1.17 darwin/amd64`.

When I run the command as follows, I get some errors in the picture.

```sh
go build -o test test-adapter/main.go
```

image

**How to fix the bug?**

The reason is related to [kube-openapi's changes](https://github.com/kubernetes/kube-openapi/pull/234), so I reproduce the `zz_generated.openapi.go` and it works out as follows.

image

### CODE REVIEW

**Comment by dashanji** [comment]
Hi, there, could you please review the PR?  @EppO @mortent @Atoms

**Comment by dgrisonnet** [comment]
Thank you for the PR @dashanji 

/lgtm
/approve

**Pull request merged**
