### PR TITLE
Fix openapi rendering issue and build tooling improvements

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Resolves "Failed to build open api spec for root: non-body Restful parameter type should be a simple type, but got : v1.ResourceVersionMatch"

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@johanneswuerbach wonderful, thank you! reviewing and also cc'ing @dgrisonnet

**Comment by s-urbaniak** [comment]
lgtm, again, thank you so much @johanneswuerbach ! :rocket:

**Comment by s-urbaniak** [comment]
@johanneswuerbach do you want to tackle the bump in prometheus-adapter as well? Once done, I can release a 0.8.2 immediately.

**Comment by johanneswuerbach** [comment]
Yes, working on it now :-)

**Comment by s-urbaniak** [comment]
@johanneswuerbach fyi: @dgrisonnet found out something is broken with the build though.

**Comment by johanneswuerbach** [comment]
Let me know if you need any help, here is the k8s-prometheus-adapter PR https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/335

**Comment by dgrisonnet** [comment]
The fix seems to be working properly as far as I tested with the test-adapter so I think we can move on with the prometheus-adapter bump.
However, when I was trying to build this project in a freshly cloned repo, the openapi files were not getting generated, which resulted in build errors.

**Pull request merged**
